# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerPeer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from resources import images_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 372)
        Dialog.setStyleSheet("")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(220, 39, 401, 261))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.StartBtn = QtWidgets.QPushButton(Dialog)
        self.StartBtn.setGeometry(QtCore.QRect(220, 310, 171, 51))
        self.StartBtn.setObjectName("StartBtn")
        self.TopLabel = QtWidgets.QLabel(Dialog)
        self.TopLabel.setGeometry(QtCore.QRect(220, 0, 401, 39))
        self.TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TopLabel.setObjectName("TopLabel")
        self.CloseBtn = QtWidgets.QPushButton(Dialog)
        self.CloseBtn.setGeometry(QtCore.QRect(450, 310, 171, 51))
        self.CloseBtn.setObjectName("CloseBtn")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(110, 320, 101, 21))
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(3, 33, 100, 281))
        self.splitter.setStyleSheet("")
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.waitTimeLabel = QtWidgets.QLabel(self.splitter)
        self.waitTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.waitTimeLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.waitTimeLabel.setStyleSheet("")
        self.waitTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waitTimeLabel.setObjectName("waitTimeLabel")
        self.msgNumsLabel = QtWidgets.QLabel(self.splitter)
        self.msgNumsLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.msgNumsLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.msgNumsLabel.setStyleSheet("")
        self.msgNumsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.msgNumsLabel.setObjectName("msgNumsLabel")
        self.QueueUrlLabel = QtWidgets.QLabel(self.splitter)
        self.QueueUrlLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.QueueUrlLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.QueueUrlLabel.setStyleSheet("")
        self.QueueUrlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.QueueUrlLabel.setObjectName("QueueUrlLabel")
        self.regionLabel = QtWidgets.QLabel(self.splitter)
        self.regionLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.regionLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.regionLabel.setStyleSheet("")
        self.regionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.regionLabel.setObjectName("regionLabel")
        self.visibilityTimeLabel = QtWidgets.QLabel(self.splitter)
        self.visibilityTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.visibilityTimeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.visibilityTimeLabel.setStyleSheet("")
        self.visibilityTimeLabel.setObjectName("visibilityTimeLabel")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(110, 39, 100, 261))
        self.splitter_2.setStyleSheet("")
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.waitTime_Input = QtWidgets.QLineEdit(self.splitter_2)
        self.waitTime_Input.setMinimumSize(QtCore.QSize(100, 30))
        self.waitTime_Input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.waitTime_Input.setStyleSheet("")
        self.waitTime_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.waitTime_Input.setObjectName("waitTime_Input")
        self.msgNums_Input = QtWidgets.QLineEdit(self.splitter_2)
        self.msgNums_Input.setMinimumSize(QtCore.QSize(100, 30))
        self.msgNums_Input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.msgNums_Input.setStyleSheet("")
        self.msgNums_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.msgNums_Input.setObjectName("msgNums_Input")
        self.QueueUrl_Input = QtWidgets.QLineEdit(self.splitter_2)
        self.QueueUrl_Input.setMinimumSize(QtCore.QSize(100, 30))
        self.QueueUrl_Input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.QueueUrl_Input.setStyleSheet("")
        self.QueueUrl_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.QueueUrl_Input.setObjectName("QueueUrl_Input")
        self.region_Input = QtWidgets.QLineEdit(self.splitter_2)
        self.region_Input.setMinimumSize(QtCore.QSize(100, 30))
        self.region_Input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.region_Input.setStyleSheet("")
        self.region_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.region_Input.setObjectName("region_Input")
        self.visibilityTime_Input = QtWidgets.QLineEdit(self.splitter_2)
        self.visibilityTime_Input.setMinimumSize(QtCore.QSize(100, 30))
        self.visibilityTime_Input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.visibilityTime_Input.setStyleSheet("")
        self.visibilityTime_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.visibilityTime_Input.setObjectName("visibilityTime_Input")

        self.retranslateUi(Dialog)
        self.waitTime_Input.textChanged['QString'].connect(Dialog.setSendBtnEnble)
        self.QueueUrl_Input.textChanged['QString'].connect(Dialog.setSendBtnEnble)
        self.msgNums_Input.textChanged['QString'].connect(Dialog.setSendBtnEnble)
        self.region_Input.textChanged['QString'].connect(Dialog.setSendBtnEnble)
        self.visibilityTime_Input.textChanged['QString'].connect(Dialog.setSendBtnEnble)
        self.StartBtn.clicked.connect(Dialog.startEvent)
        self.CloseBtn.clicked.connect(Dialog.close_Event)
        self.checkBox.clicked.connect(Dialog.setRemember)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Order"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "SenderId"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Messages"))
        self.StartBtn.setText(_translate("Dialog", "Start"))
        self.TopLabel.setText(_translate("Dialog", "Recieve Messages"))
        self.CloseBtn.setText(_translate("Dialog", "Close"))
        self.checkBox.setText(_translate("Dialog", "Remember"))
        self.waitTimeLabel.setText(_translate("Dialog", "wait_time"))
        self.msgNumsLabel.setText(_translate("Dialog", "num_msgs"))
        self.QueueUrlLabel.setText(_translate("Dialog", "queue_url"))
        self.regionLabel.setText(_translate("Dialog", "region"))
        self.visibilityTimeLabel.setText(_translate("Dialog", "visibility_time"))


